name: Docker cache build

on:
  push:
    branches:
      - main

jobs:
  docker-cache:
    uses: TrustlessComputer/tc-github-action-templates/.github/workflows/docker-build-cache.yaml@main
    with:
      DOCKER_IMAGE_NAME: new-bitcoin-city
      DOCKERFILE_NAME: Dockerfile.cache

