name: Docker production with static assets build

on:
  push:
    tags:
      - 'v[12].[0-9]+.[0-9]+'

jobs:
  build-new-bitcoin-city-production-static:
    uses: TrustlessComputer/tc-github-action-templates/.github/workflows/docker-build-and-push.yaml@main
    with:
      DOCKER_IMAGE_NAME: play-modular-website
      DOCKERFILE_NAME: Dockerfile
      CONCURRENCY_GROUP: docker_build_production
      RUNNER_TAG: ubuntu-latest-m
      DOCKER_AUTOPUSH: true
    secrets:
      GCLOUD_DEV_SERVICE_ACCOUNT_JSON: ${{ secrets.GCLOUD_DEV_SERVICE_ACCOUNT_JSON }}
